### ISSUE TITLE
Philes says: "IPFS daemon not running."

### ISSUE THREAD

**Issue by JayBrown** [computes/philes#1]
Just wanted to test philes.co, but it's telling me on the bottom of the page that the "IPFS daemon [is] not running", even though is enabled (Safari 10.1, OS X 10.11.6, ipfs 0.4.8; same with Chrome). So when I try to save a philes note, it says that there's a connection error:

```
%7B%22code%22:%22ECONNREFUSED%22,%22errno%22:%22ECONNREFUSED%22,%22syscall%22:%22connect%22,%22address%22:%22127.0.0.1%22,%22port%22:5001%7D
```

**Comment by computes** [comment]
Try running the Go version of the IPFS daemon from your terminal window. https://github.com/ipfs/go-ipfs

**Comment by JayBrown** [comment]
Yup, that's what I'm doing. Installed & always up-to-date with Homebrew, which (to my knowledge) should be the same go-ipfs as the ones available here: https://ipfs.io/ipns/dist.ipfs.io/#go-ipfs … `ipfs daemon` without errors, ipfs works fine in general. So I don't know what the problem could be.

**Comment by computes** [comment]
Not sure either. Just confirmed that it's working for me on both Chrome and Safari while running go ipfs in terminal.
